EOS: X
SOS: X
vocab:
- '

    '
- ' '
- '"'
- '#'
- ''''
- (
- )
- +
- ','
- '-'
- .
- /
- '0'
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- ':'
- <
- '='
- '>'
- '@'
- A
- B
- C
- D
- E
- F
- G
- H
- K
- L
- M
- Q
- X
- '['
- ']'
- ^
- _
- a
- b
- c
- d
- e
- f
- g
- i
- l
- m
- n
- o
- p
- r
- u
- z
- '|'
- '~'
